/authenticate:
  post:
    summary: "authenticate an user"
    operationId: "createAuthenticationToken"
    responses:
      "200":
        description: "OK"
---
/diary:
  get:
    summary: "GET diary"
    operationId: "diary"
    responses:
      "200":
        description: "OK"
---
/offer/:
  get:
    summary: "GET an offer by PackageId"
    operationId: "getOffersByPackageID"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/offer/accept/:
  delete:
    summary: "Accept an offer(Delete the remaining ones)"
    operationId: "acceptOffer"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/offer/create:
  post:
    summary: "POST create an offer"
    operationId: "createOffer"
    responses:
      "200":
        description: "OK"
---
/offer/delete/:
  delete:
    summary: "DELETE an offer by ID"
    operationId: "deleteOffer"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/offer/edit/:
  put:
    summary: "Edit an offer "
    operationId: "updateOffer"
    responses:
      "200":
        description: "OK"
---
/offer/reject/:
  delete:
    summary: "Reject an offer"
    operationId: "rejectOffer"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/package/:
  get:
    summary: "GET a package by ID"
    operationId: "getPackageById"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/package/create:
  post:
    summary: "Create a package"
    operationId: "createPackage"
    responses:
      "200":
        description: "OK"
---
/package/delete/:
  delete:
    summary: "DELETE a package by ID "
    operationId: "deletePackage"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/package/edit/:
  put:
    summary: "Edit a package"
    operationId: "updatePackage"
    responses:
      "200":
        description: "OK"
---
/package/list:
  get:
    summary: "GET all package"
    operationId: "getAllPackages"
    responses:
      "200":
        description: "OK"
---
/package/transporter/:
  get:
    summary: "GET all package by transporter(Which belongs to him)"
    operationId: "getPackagesByTransporter"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/package/user/:
  get:
    summary: "GET all package by User(Which belongs to him)"
    operationId: "getPackagesByUser"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/register:
  post:
    summary: "Register an user to the system"
    operationId: "saveUser"
    responses:
      "200":
        description: "OK"
---
/review/:
  get:
    summary: "GET a review by packageId"
    operationId: "getReviewByPackageId"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/review/create:
  post:
    summary: "Create a review"
    operationId: "createReview"
    responses:
      "200":
        description: "OK"
---
/review/delete/:
  delete:
    summary: "DELETE a review by Id"
    operationId: "deleteReview"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/review/edit/:
  put:
    summary: "Edit a review by ID"
    operationId: "editReviewById"
    responses:
      "200":
        description: "OK"
---
/review/transporter/:
  get:
    summary: "Get all review by Transporter(Which belongs to him)"
    operationId: "getReviewsByTransporter"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/user/:
  get:
    summary: "GET an user by ID"
    operationId: "getUserById"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/user/delete/:
  delete:
    summary: "DELETE an User"
    operationId: "deleteUser"
    parameters:
      - name: "id"
        in: "query"
        required: true
        schema:
          type: "string"
    responses:
      "200":
        description: "OK"
---
/user/edit/:
  put:
    summary: "Edit a user"
    operationId: "updateUser"
    responses:
      "200":
        description: "OK"
---
/user/list:
  get:
    summary: "GET all user"
    operationId: "getAllUsers"
    responses:
      "200":
        description: "OK"


  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        telephone:
          type: string
        size:
          type: string
        role:
          type: string
    Package:
      type: object
      properties:
        id:
          type: string
        userID:
          type: string
        transporterID:
          type: string
        from:
          type: string
        to:
          type: string
        creation date:
          type: date
        deadline:
          type: date
        price:
          type: integer
        weight:
          type: integer
        size:
          type: string
        status:
          type: string
    Review:
      type: object
      properties:
        id:
          type: string
        transporterID:
          type: string
        packageID:
          type: string
        time:
          type: date
        rating:
          type: integer
        description:
          type: string
        CustomerUsername:
          type: string
    Offer:
      type: object
      properties:
        id:
          type: string
        transporterID:
          type: string
        packageID:
          type: string
        price:
          type: integer
    Location:
      type:
      properties:
    Size :
      type:
      properties:
    Status :
      type:
      properties:
    JwtResponse:
      type:
      properties:
    JwtRequest:
      type:
      properties:
    Role:
      type:
      properties:
